# =============================================================================
# ArgoCD Application - Admin App
# =============================================================================
# React admin portal for platform management
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: admin-app
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: control-plane
    environment: '{{.Values.environment}}'
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ananta-platform

  source:
    repoURL: https://github.com/ananta-platform/ananta-platform-saas.git
    targetRevision: HEAD
    path: infrastructure/kubernetes/helm/admin-app

    helm:
      releaseName: admin-app
      valueFiles:
        - values.yaml
        - values-{{.Values.environment}}.yaml

      values: |
        fullnameOverride: admin-app

        image:
          repository: ghcr.io/ananta-platform/admin-app
          pullPolicy: IfNotPresent

        service:
          type: ClusterIP
          port: 80

        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/proxy-body-size: "10m"
            nginx.ingress.kubernetes.io/configuration-snippet: |
              add_header X-Frame-Options "SAMEORIGIN" always;
              add_header X-Content-Type-Options "nosniff" always;
              add_header X-XSS-Protection "1; mode=block" always;
          hosts:
            - host: admin.{{.Values.domain}}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: admin-app-tls
              hosts:
                - admin.{{.Values.domain}}

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 6
          targetCPUUtilizationPercentage: 70

        # Nginx configuration for SPA
        nginx:
          config: |
            server {
              listen 80;
              root /usr/share/nginx/html;
              index index.html;

              location / {
                try_files $uri $uri/ /index.html;
              }

              location /health {
                return 200 'OK';
                add_header Content-Type text/plain;
              }

              location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
              }
            }

        # Runtime config injected at startup
        runtimeConfig:
          VITE_API_URL: https://api.{{.Values.domain}}
          VITE_KEYCLOAK_URL: https://auth.{{.Values.domain}}
          VITE_KEYCLOAK_REALM: ananta
          VITE_KEYCLOAK_CLIENT_ID: admin-app

  destination:
    server: https://kubernetes.default.svc
    namespace: ananta-{{.Values.environment}}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

  info:
    - name: Documentation
      value: https://docs.ananta-platform.io/apps/admin
    - name: Team
      value: frontend-team
