# =============================================================================
# ArgoCD Application - Redis
# =============================================================================
# In-memory cache and session store
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: infrastructure
    environment: '{{.Values.environment}}'
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ananta-platform

  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.6.1
    chart: redis

    helm:
      releaseName: redis
      values: |
        fullnameOverride: redis

        image:
          tag: 7.2.3

        architecture: replication

        auth:
          enabled: true
          existingSecret: redis-secret
          existingSecretPasswordKey: redis-password

        master:
          replicaCount: 1
          persistence:
            enabled: true
            size: 10Gi
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi

        replica:
          replicaCount: 2
          persistence:
            enabled: true
            size: 10Gi
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi

        sentinel:
          enabled: true
          quorum: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            interval: 30s

        networkPolicy:
          enabled: true
          allowExternal: true

        # Memory configuration
        commonConfiguration: |
          maxmemory 1gb
          maxmemory-policy volatile-lru
          notify-keyspace-events ""

  destination:
    server: https://kubernetes.default.svc
    namespace: cache-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

  revisionHistoryLimit: 5

  info:
    - name: Documentation
      value: https://docs.ananta-platform.io/infrastructure/redis
    - name: Team
      value: platform-team
