# =============================================================================
# ArgoCD Application - Supabase
# =============================================================================
# Open-source Firebase alternative (PostgreSQL + Auth + Storage + Realtime)
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: infrastructure
    environment: dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ananta-platform

  source:
    repoURL: https://github.com/ananta-platform/ananta-platform-saas.git
    targetRevision: develop
    path: infrastructure/kubernetes/helm/supabase

    helm:
      releaseName: supabase
      valueFiles:
        - values.yaml
        - values-dev.yaml

      values: |
        studio:
          replicaCount: 1
          image:
            repository: supabase/studio
            tag: 20231123-64a766c

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        kong:
          replicaCount: 2
          image:
            repository: kong
            tag: 3.4.2-alpine

          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi

        auth:
          replicaCount: 2
          image:
            repository: supabase/gotrue
            tag: v2.99.0

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

        rest:
          replicaCount: 2
          image:
            repository: postgrest/postgrest
            tag: v11.2.2

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

        realtime:
          replicaCount: 2
          image:
            repository: supabase/realtime
            tag: v2.25.35

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

        storage:
          replicaCount: 2
          image:
            repository: supabase/storage-api
            tag: v0.43.11

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

        meta:
          replicaCount: 1
          image:
            repository: supabase/postgres-meta
            tag: v0.68.0

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

        db:
          enabled: false
          external:
            host: postgresql.database-system.svc.cluster.local
            port: 5432
            database: postgres
            user: postgres
            existingSecret: postgresql-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: database-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

  revisionHistoryLimit: 5

  info:
    - name: Documentation
      value: https://supabase.com/docs
