# =============================================================================
# Infracost Usage File - Production Environment
# =============================================================================
# Estimated usage for cost calculation in production environment
# =============================================================================

version: 0.1

resource_usage:
  # ---------------------------------------------------------------------------
  # AWS Resources
  # ---------------------------------------------------------------------------

  # NAT Gateways (multiple for HA)
  aws_nat_gateway.main[0]:
    monthly_data_processed_gb: 1000

  aws_nat_gateway.main[1]:
    monthly_data_processed_gb: 1000

  aws_nat_gateway.main[2]:
    monthly_data_processed_gb: 1000

  # RDS PostgreSQL - Control Plane (Multi-AZ)
  aws_db_instance.control_plane:
    monthly_standard_io_requests: 500000000  # 500M requests (production scale)
    monthly_additional_backup_storage_gb: 200

  # RDS PostgreSQL - App Plane/Supabase (Multi-AZ)
  aws_db_instance.app_plane:
    monthly_standard_io_requests: 300000000  # 300M requests
    monthly_additional_backup_storage_gb: 150

  # RDS PostgreSQL - Temporal (Multi-AZ)
  aws_db_instance.temporal:
    monthly_standard_io_requests: 400000000  # 400M requests (heavy workflow)
    monthly_additional_backup_storage_gb: 200

  # RDS PostgreSQL - Keycloak (Multi-AZ)
  aws_db_instance.keycloak:
    monthly_standard_io_requests: 200000000  # 200M requests
    monthly_additional_backup_storage_gb: 100

  # RDS PostgreSQL - Components V2 (Multi-AZ)
  aws_db_instance.components:
    monthly_standard_io_requests: 150000000  # 150M requests
    monthly_additional_backup_storage_gb: 100

  # ElastiCache Redis (Multi-AZ with replicas)
  aws_elasticache_replication_group.main:
    snapshot_storage_size_gb: 100

  # S3 Buckets
  aws_s3_bucket.assets:
    standard:
      storage_gb: 2000
      monthly_tier_1_requests: 5000000      # 5M PUT/POST
      monthly_tier_2_requests: 25000000     # 25M GET
      monthly_data_transfer_gb: 2000
    intelligent_tiering:
      frequent_access_storage_gb: 1000
      infrequent_access_storage_gb: 500
    glacier_flexible_retrieval:
      storage_gb: 500

  aws_s3_bucket.backups:
    standard:
      storage_gb: 1000
      monthly_tier_1_requests: 200000
      monthly_tier_2_requests: 1000000
      monthly_data_transfer_gb: 100
    glacier_deep_archive:
      storage_gb: 5000

  # CloudWatch Logs
  aws_cloudwatch_log_group.application:
    monthly_data_ingested_gb: 200
    monthly_data_scanned_gb: 100

  # ECS Fargate Services (Production Scale)
  aws_ecs_service.tenant_management:
    monthly_cpu_hours: 7200             # 10 vCPU * 24h * 30 days
    monthly_memory_gb_hours: 14400      # 20GB * 24h * 30 days

  aws_ecs_service.temporal_worker:
    monthly_cpu_hours: 7200
    monthly_memory_gb_hours: 14400

  aws_ecs_service.cns_service:
    monthly_cpu_hours: 5400             # 7.5 vCPU
    monthly_memory_gb_hours: 10800      # 15GB

  aws_ecs_service.customer_portal:
    monthly_cpu_hours: 3600             # 5 vCPU
    monthly_memory_gb_hours: 7200       # 10GB

  aws_ecs_service.admin_app:
    monthly_cpu_hours: 1440             # 2 vCPU
    monthly_memory_gb_hours: 2880       # 4GB

  # Application Load Balancer
  aws_lb.main:
    monthly_lcu_hours: 2000

  # WAF
  aws_wafv2_web_acl.main:
    monthly_requests: 50000000          # 50M requests

  # Secrets Manager
  aws_secretsmanager_secret.main:
    monthly_api_requests: 500000

  # Data Transfer (High Production Volume)
  aws_data_transfer.cross_az:
    monthly_gb: 2000

  aws_data_transfer.internet_egress:
    monthly_gb: 5000                    # 5TB egress

  # ---------------------------------------------------------------------------
  # GCP Resources
  # ---------------------------------------------------------------------------

  # Cloud SQL (HA)
  google_sql_database_instance.control_plane:
    disk_size: 1000

  google_sql_database_instance.app_plane:
    disk_size: 500

  google_sql_database_instance.temporal:
    disk_size: 500

  # Memorystore Redis (HA)
  google_redis_instance.main:
    storage_size_gb: 100

  # GKE Cluster
  google_container_cluster.main:
    monthly_egress_data_transfer_gb:
      same_continent: 2000
      worldwide: 1000
      asia: 500

  # Cloud Storage
  google_storage_bucket.assets:
    storage_gb: 2000
    monthly_class_a_operations: 5000000
    monthly_class_b_operations: 25000000
    monthly_egress_data_transfer_gb:
      same_continent: 4000
      worldwide: 2000
      asia: 1000

  google_storage_bucket.backups:
    storage_gb: 1000
    coldline:
      storage_gb: 3000
    archive:
      storage_gb: 10000

  # Cloud NAT (multiple for regions)
  google_compute_router_nat.main:
    monthly_data_processed_gb: 2000

  google_compute_router_nat.secondary:
    monthly_data_processed_gb: 2000

  # Cloud Armor
  google_compute_security_policy.main:
    monthly_requests: 50000000

  # Secret Manager
  google_secret_manager_secret.main:
    monthly_access_operations: 500000
