# Generated by Django 4.2.7 on 2025-10-28 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        db_index=True,
                        default="member",
                        max_length=20,
                    ),
                ),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("mfa_secret", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "oauth_provider",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("oauth_id", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "db_table": "users_v2",
            },
        ),
        migrations.CreateModel(
            name="BOM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boms_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "boms_v2",
            },
        ),
        migrations.CreateModel(
            name="ParameterNormalization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parameter_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("display_name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("string", "String"),
                            ("boolean", "Boolean"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("vendor_aliases", models.JSONField(default=list)),
                ("parse_patterns", models.JSONField(default=list)),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "parameter_normalizations",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("max_users", models.IntegerField(default=5)),
                ("max_components", models.IntegerField(default=10000)),
                ("max_storage_gb", models.IntegerField(default=10)),
                ("current_users_count", models.IntegerField(default=0)),
                ("current_components_count", models.IntegerField(default=0)),
                (
                    "current_storage_gb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenants_v2",
                "indexes": [
                    models.Index(
                        fields=["subscription_status"],
                        name="tenants_v2_subscri_d34fce_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="tenants_v2_created_58f7ba_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mpn", models.CharField(db_index=True, max_length=255)),
                ("manufacturer_name", models.CharField(db_index=True, max_length=255)),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField()),
                (
                    "lifecycle_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "datasheet_s3_key",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "datasheet_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "model_3d_s3_key",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "image_s3_key",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("vendor_source", models.CharField(max_length=50)),
                ("raw_vendor_data", models.JSONField(default=dict)),
                ("normalization_confidence", models.FloatField(blank=True, null=True)),
                ("normalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "components_v2",
            },
        ),
        migrations.CreateModel(
            name="CategoryMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor", models.CharField(db_index=True, max_length=50)),
                ("vendor_category", models.CharField(db_index=True, max_length=500)),
                ("standard_category", models.CharField(max_length=100)),
                ("confidence", models.FloatField()),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_category_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "category_mappings_cache",
            },
        ),
        migrations.CreateModel(
            name="BOMLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_designator", models.CharField(max_length=100)),
                ("mpn_raw", models.CharField(max_length=255)),
                ("manufacturer_raw", models.CharField(blank=True, max_length=255)),
                ("description_raw", models.TextField(blank=True)),
                ("quantity", models.IntegerField(default=1)),
                ("match_confidence", models.FloatField(blank=True, null=True)),
                (
                    "match_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exact", "Exact MPN Match"),
                            ("fuzzy", "Fuzzy Match"),
                            ("manual", "Manual Override"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("manually_selected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="catalog.bom",
                    ),
                ),
                (
                    "matched_component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bom_line_items",
                        to="catalog.component",
                    ),
                ),
            ],
            options={
                "db_table": "bom_line_items_v2",
            },
        ),
        migrations.AddField(
            model_name="bom",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.tenant"
            ),
        ),
        migrations.CreateModel(
            name="BillingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("subscription_created", "Subscription Created"),
                            ("subscription_updated", "Subscription Updated"),
                            ("subscription_canceled", "Subscription Canceled"),
                            ("payment_succeeded", "Payment Succeeded"),
                            ("payment_failed", "Payment Failed"),
                            ("trial_started", "Trial Started"),
                            ("trial_ending", "Trial Ending"),
                            ("trial_expired", "Trial Expired"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_events",
                        to="catalog.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "billing_events_v2",
            },
        ),
        migrations.CreateModel(
            name="AlertPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alert_type", models.CharField(max_length=50)),
                ("enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "alert_preferences_v2",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("lifecycle_change", "Lifecycle Status Change"),
                            ("price_increase", "Price Increase"),
                            ("price_decrease", "Price Decrease"),
                            ("stock_low", "Low Stock"),
                            ("stock_available", "Stock Available"),
                            ("compliance_issue", "Compliance Issue"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("old_value", models.CharField(blank=True, max_length=255, null=True)),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("read", models.BooleanField(default=False)),
                ("dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="catalog.component",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "alerts_v2",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="catalog.tenant",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="VendorPricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor", models.CharField(db_index=True, max_length=50)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("pricing_tiers", models.JSONField(default=list)),
                ("in_stock", models.BooleanField(default=False)),
                ("stock_quantity", models.IntegerField(blank=True, null=True)),
                ("lead_time_days", models.IntegerField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="catalog.component",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_pricing_v2",
                "indexes": [
                    models.Index(
                        fields=["vendor", "in_stock"],
                        name="vendor_pric_vendor_c3c4a7_idx",
                    )
                ],
                "unique_together": {("component", "vendor")},
            },
        ),
        migrations.CreateModel(
            name="ComponentParameter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parameter_id", models.CharField(db_index=True, max_length=100)),
                ("parameter_display_name", models.CharField(max_length=255)),
                ("value", models.JSONField()),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("type", models.CharField(max_length=20)),
                ("original_name", models.CharField(max_length=255)),
                ("original_value", models.CharField(max_length=500)),
                ("normalization_confidence", models.FloatField(blank=True, null=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="catalog.component",
                    ),
                ),
            ],
            options={
                "db_table": "component_parameters_v2",
                "indexes": [
                    models.Index(
                        fields=["component", "parameter_id"],
                        name="component_p_compone_577750_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["tenant", "category"], name="components__tenant__d9be7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["tenant", "manufacturer_name"],
                name="components__tenant__26ba5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["vendor_source"], name="components__vendor__bed718_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["lifecycle_status"], name="components__lifecyc_42de3c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="component",
            unique_together={("tenant", "mpn", "manufacturer_name")},
        ),
        migrations.AlterUniqueTogether(
            name="categorymapping",
            unique_together={("vendor", "vendor_category")},
        ),
        migrations.AddIndex(
            model_name="bomlineitem",
            index=models.Index(
                fields=["bom", "mpn_raw"], name="bom_line_it_bom_id_a45f15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bom",
            index=models.Index(
                fields=["tenant", "status"], name="boms_v2_tenant__9c6dce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bom",
            index=models.Index(
                fields=["created_by"], name="boms_v2_created_fd2b7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingevent",
            index=models.Index(
                fields=["tenant", "event_type"], name="billing_eve_tenant__75484a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingevent",
            index=models.Index(
                fields=["created_at"], name="billing_eve_created_7b52c8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alertpreference",
            unique_together={("user", "alert_type")},
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["tenant", "alert_type", "read"],
                name="alerts_v2_tenant__62beca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["component", "created_at"], name="alerts_v2_compone_cfddeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["tenant", "email"], name="users_v2_tenant__36dfd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["oauth_provider", "oauth_id"],
                name="users_v2_oauth_p_70700c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_v2_role_2635a9_idx"),
        ),
    ]
