# =============================================================================
# ArgoCD Project - Ananta Platform
# =============================================================================
# Parent project for all Ananta Platform SaaS microservices
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ananta-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: ananta-platform
    app.kubernetes.io/part-of: ananta-saas
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Ananta Platform SaaS - Multi-tenant control plane and app plane services

  # Source repositories
  sourceRepos:
    - 'https://github.com/siddh7007/Ananta-Platform-Saas.git'
    - 'ghcr.io/siddh7007/ananta/*'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://helm.releases.hashicorp.com'
    - 'https://charts.jetstack.io'
    - 'https://kubernetes.github.io/ingress-nginx'
    - 'https://argoproj.github.io/argo-helm'
    - 'https://grafana.github.io/helm-charts'
    - 'https://prometheus-community.github.io/helm-charts'

  # Destination clusters and namespaces
  destinations:
    # Control Plane
    - namespace: control-plane
      server: https://kubernetes.default.svc

    # App Plane
    - namespace: app-plane
      server: https://kubernetes.default.svc

    # ArgoCD namespace (for self-management)
    - namespace: argocd
      server: https://kubernetes.default.svc

    # Shared services
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: logging
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc

    # Infrastructure services
    - namespace: keycloak-system
      server: https://kubernetes.default.svc
    - namespace: temporal-system
      server: https://kubernetes.default.svc
    - namespace: rabbitmq-system
      server: https://kubernetes.default.svc
    - namespace: cache-system
      server: https://kubernetes.default.svc
    - namespace: novu-system
      server: https://kubernetes.default.svc
    - namespace: database-system
      server: https://kubernetes.default.svc

  # Cluster resource allow list
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: PersistentVolume
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: scheduling.k8s.io
      kind: PriorityClass
    - group: networking.k8s.io
      kind: IngressClass
    - group: storage.k8s.io
      kind: StorageClass

  # Namespace resource allow list
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: apps
      kind: '*'
    - group: batch
      kind: '*'
    - group: networking.k8s.io
      kind: '*'
    - group: autoscaling
      kind: '*'
    - group: policy
      kind: '*'
    - group: monitoring.coreos.com
      kind: '*'
    - group: cert-manager.io
      kind: '*'

  # Roles for project access
  roles:
    - name: admin
      description: Full admin access to all applications
      policies:
        - p, proj:ananta-platform:admin, applications, *, ananta-platform/*, allow
        - p, proj:ananta-platform:admin, repositories, *, ananta-platform/*, allow
        - p, proj:ananta-platform:admin, clusters, *, ananta-platform/*, allow
        - p, proj:ananta-platform:admin, logs, get, ananta-platform/*, allow
        - p, proj:ananta-platform:admin, exec, create, ananta-platform/*, allow
      groups:
        - platform-admins
        - devops-team

    - name: developer
      description: Read-only access with sync permissions
      policies:
        - p, proj:ananta-platform:developer, applications, get, ananta-platform/*, allow
        - p, proj:ananta-platform:developer, applications, sync, ananta-platform/*, allow
        - p, proj:ananta-platform:developer, logs, get, ananta-platform/*, allow
      groups:
        - developers

    - name: viewer
      description: Read-only access
      policies:
        - p, proj:ananta-platform:viewer, applications, get, ananta-platform/*, allow
        - p, proj:ananta-platform:viewer, logs, get, ananta-platform/*, allow
      groups:
        - viewers
        - stakeholders

  # Sync windows for production
  syncWindows:
    # Allow syncs during business hours for dev
    - kind: allow
      schedule: '0 9-18 * * 1-5'
      duration: 10h
      applications:
        - '*-dev'
      namespaces:
        - 'ananta-dev*'
      manualSync: true

    # Deny production syncs during peak hours
    - kind: deny
      schedule: '0 9-17 * * 1-5'
      duration: 8h
      applications:
        - '*-prod'
      namespaces:
        - 'ananta-prod*'
      manualSync: false

    # Allow production syncs during maintenance window
    - kind: allow
      schedule: '0 2 * * 6'
      duration: 4h
      applications:
        - '*-prod'
      namespaces:
        - 'ananta-prod*'
      manualSync: true

  # Signature keys for signed commits (optional)
  signatureKeys: []

  # Orphaned resources monitoring
  orphanedResources:
    warn: true
    ignore:
      - group: ''
        kind: ConfigMap
        name: kube-root-ca.crt
